// <auto-generated />
using System;
using DrugPreventionSystem.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrugPreventionSystem.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250605084425_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrugPreventionSystem.DataAccess.Models.Consultant", b =>
                {
                    b.Property<Guid>("ConsultantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("consultant_id");

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("bio");

                    b.Property<decimal?>("ConsultationFee")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("consultation_fee");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit")
                        .HasColumnName("is_available");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("license_number");

                    b.Property<string>("Qualifications")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("qualifications");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("rating");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("specialization");

                    b.Property<int>("TotalConsultations")
                        .HasColumnType("int")
                        .HasColumnName("total_consultations");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("WorkingHours")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("working_hours");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnName("years_of_experience");

                    b.HasKey("ConsultantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("consultants");
                });

            modelBuilder.Entity("DrugPreventionSystem.DataAccess.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("RoleId");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 6, 5, 15, 44, 24, 416, DateTimeKind.Local).AddTicks(8457),
                            Description = "System Administrator",
                            IsActive = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 6, 5, 15, 44, 24, 416, DateTimeKind.Local).AddTicks(8470),
                            Description = "System Manager",
                            IsActive = true,
                            RoleName = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 6, 5, 15, 44, 24, 416, DateTimeKind.Local).AddTicks(8472),
                            Description = "Staff Member",
                            IsActive = true,
                            RoleName = "Staff"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2025, 6, 5, 15, 44, 24, 416, DateTimeKind.Local).AddTicks(8473),
                            Description = "Professional Consultant",
                            IsActive = true,
                            RoleName = "Consultant"
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2025, 6, 5, 15, 44, 24, 416, DateTimeKind.Local).AddTicks(8474),
                            Description = "Registered Member",
                            IsActive = true,
                            RoleName = "Member"
                        });
                });

            modelBuilder.Entity("DrugPreventionSystem.DataAccess.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("bit")
                        .HasColumnName("email_verified");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("697a6963-2641-46de-a266-b46c685cf8ba"),
                            CreatedAt = new DateTime(2025, 6, 5, 15, 44, 24, 553, DateTimeKind.Local).AddTicks(3957),
                            Email = "admin@example.com",
                            EmailVerified = true,
                            IsActive = true,
                            PasswordHash = "$2a$11$o19Ma.8k2U6PEXAXMnKUNeHxmzkPRl39YMVNmyDo5SMnNINW4J57.",
                            RoleId = 1,
                            Username = "admin_user"
                        },
                        new
                        {
                            UserId = new Guid("dfe5c967-ed12-4f41-9f3a-ef3d9db32f80"),
                            CreatedAt = new DateTime(2025, 6, 5, 15, 44, 24, 553, DateTimeKind.Local).AddTicks(3961),
                            Email = "manager@example.com",
                            EmailVerified = true,
                            IsActive = true,
                            PasswordHash = "$2a$11$o19Ma.8k2U6PEXAXMnKUNeHxmzkPRl39YMVNmyDo5SMnNINW4J57.",
                            RoleId = 2,
                            Username = "manager_user"
                        },
                        new
                        {
                            UserId = new Guid("7385b13a-ccff-4213-92e6-0f20421c95c4"),
                            CreatedAt = new DateTime(2025, 6, 5, 15, 44, 24, 553, DateTimeKind.Local).AddTicks(3964),
                            Email = "staff@example.com",
                            EmailVerified = true,
                            IsActive = true,
                            PasswordHash = "$2a$11$o19Ma.8k2U6PEXAXMnKUNeHxmzkPRl39YMVNmyDo5SMnNINW4J57.",
                            RoleId = 3,
                            Username = "staff_user"
                        },
                        new
                        {
                            UserId = new Guid("b5b82f90-6d92-45ea-804e-ab55ec5395e8"),
                            CreatedAt = new DateTime(2025, 6, 5, 15, 44, 24, 553, DateTimeKind.Local).AddTicks(3966),
                            Email = "consultant@example.com",
                            EmailVerified = true,
                            IsActive = true,
                            PasswordHash = "$2a$11$o19Ma.8k2U6PEXAXMnKUNeHxmzkPRl39YMVNmyDo5SMnNINW4J57.",
                            RoleId = 4,
                            Username = "consultant_user"
                        });
                });

            modelBuilder.Entity("DrugPreventionSystem.DataAccess.Models.UserProfile", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("profile_id");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("AgeGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("age_group");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("avatar_url");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("education_level");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("occupation");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("ProfileId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles");
                });

            modelBuilder.Entity("DrugPreventionSystem.DataAccess.Models.Consultant", b =>
                {
                    b.HasOne("DrugPreventionSystem.DataAccess.Models.User", "User")
                        .WithOne("Consultant")
                        .HasForeignKey("DrugPreventionSystem.DataAccess.Models.Consultant", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DrugPreventionSystem.DataAccess.Models.User", b =>
                {
                    b.HasOne("DrugPreventionSystem.DataAccess.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DrugPreventionSystem.DataAccess.Models.UserProfile", b =>
                {
                    b.HasOne("DrugPreventionSystem.DataAccess.Models.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("DrugPreventionSystem.DataAccess.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DrugPreventionSystem.DataAccess.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DrugPreventionSystem.DataAccess.Models.User", b =>
                {
                    b.Navigation("Consultant");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
